In [27]:
import polars as pl
from pathlib import Path

In [52]:
data_df = pl.DataFrame()

for file in Path("../../data/renewably_exports").glob("*.csv"):
    data_df = pl.concat([data_df, pl.read_csv(file)])

In [53]:
data_df.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ h3_index  ┆ elevation ┆ slope     ┆ aspect    ┆ … ┆ wind_10m_ ┆ wind_10m_ ┆ landcover ┆ populati │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ avg       ┆ std       ┆ ---       ┆ on_densi │
│ str       ┆ i64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ty       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 88288d140 ┆ 269       ┆ 11.815616 ┆ 297.66406 ┆ … ┆ 2.446421  ┆ 0.963432  ┆ 52        ┆ 0.033691 │
│ 9fffff    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 88268670e ┆ 2214      ┆ 10.984298 ┆ 33.48723  ┆ … ┆ 1.558011  ┆ 0.423838  ┆ 52        ┆ 0.0      │
│ bfffff    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8844c6759 ┆ 70        ┆ 2.3842168 ┆ 112.87912 ┆ … ┆ 0.884836  ┆ 0.415686  ┆ 82        ┆ 3.718725 │
│ dfffff    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 882ab5868 ┆ 172       ┆ 0.0       ┆ -0.0      ┆ … ┆ 2.272179  ┆ 1.082362  ┆ 11        ┆ 0.0      │
│ 7fffff    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 88268ab24 ┆ 2496      ┆ 5.8091083 ┆ 322.70914 ┆ … ┆ 1.16088   ┆ 0.422441  ┆ 71        ┆ 0.0      │
│ bfffff    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [54]:
final_df = pl.read_csv('../../data/final_df_processed.csv')
final_df.head()

shape: (5, 8)
┌────────────┬───────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ h3_index   ┆ lat       ┆ lng        ┆ has_turbin ┆ h3_index_ ┆ lat_right ┆ lng_right ┆ has_solar │
│ ---        ┆ ---       ┆ ---        ┆ e          ┆ right     ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64        ┆ ---        ┆ ---       ┆ f64       ┆ f64       ┆ bool      │
│            ┆           ┆            ┆ bool       ┆ str       ┆           ┆           ┆           │
╞════════════╪═══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 8826c63a69 ┆ 36.434798 ┆ -99.726666 ┆ true       ┆ 8826c63a6 ┆ 36.434798 ┆ -99.72666 ┆ false     │
│ fffff      ┆           ┆            ┆            ┆ 9fffff    ┆           ┆ 6         ┆           │
│ 88276b6627 ┆ 43.546153 ┆ -83.592551 ┆ true       ┆ 88276b662 ┆ 43.546153 ┆ -83.59255 ┆ false     │
│ fffff      ┆           ┆            ┆            ┆ 7fffff    ┆           ┆ 1         ┆           │
│ 8826666425 ┆ 40.910506 ┆ -88.966001 ┆ true       ┆ 882666642 ┆ 40.910506 ┆ -88.96600 ┆ false     │
│ fffff      ┆           ┆            ┆            ┆ 5fffff    ┆           ┆ 1         ┆           │
│ 8826e22dad ┆ 37.55112  ┆ -98.191993 ┆ true       ┆ 8826e22da ┆ 37.55112  ┆ -98.19199 ┆ false     │
│ fffff      ┆           ┆            ┆            ┆ dfffff    ┆           ┆ 3         ┆           │
│ 882603334b ┆ 42.259879 ┆ -97.320594 ┆ true       ┆ 882603334 ┆ 42.259879 ┆ -97.32059 ┆ false     │
│ fffff      ┆           ┆            ┆            ┆ bfffff    ┆           ┆ 4         ┆           │
└────────────┴───────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [55]:
df = final_df.join(data_df, on="h3_index", how="left")

In [56]:
df.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ h3_index  ┆ lat       ┆ lng       ┆ has_turbi ┆ … ┆ wind_10m_ ┆ wind_10m_ ┆ landcover ┆ populati │
│ ---       ┆ ---       ┆ ---       ┆ ne        ┆   ┆ avg       ┆ std       ┆ ---       ┆ on_densi │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ty       │
│           ┆           ┆           ┆ bool      ┆   ┆ f64       ┆ f64       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8826c63a6 ┆ 36.434798 ┆ -99.72666 ┆ true      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 9fffff    ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 88276b662 ┆ 43.546153 ┆ -83.59255 ┆ true      ┆ … ┆ 1.217305  ┆ 0.670943  ┆ 82        ┆ 4.067532 │
│ 7fffff    ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 882666642 ┆ 40.910506 ┆ -88.96600 ┆ true      ┆ … ┆ 1.124516  ┆ 0.600449  ┆ 82        ┆ 1.861619 │
│ 5fffff    ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 8826e22da ┆ 37.55112  ┆ -98.19199 ┆ true      ┆ … ┆ 1.431387  ┆ 0.903097  ┆ 82        ┆ 0.0      │
│ dfffff    ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8826e22da ┆ 37.55112  ┆ -98.19199 ┆ true      ┆ … ┆ 1.431387  ┆ 0.903097  ┆ 82        ┆ 0.0      │
│ dfffff    ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
df.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ h3_index  ┆ lat       ┆ lng       ┆ … ┆ wind_10m_ ┆ wind_10m_ ┆ landcover ┆ populati │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ avg       ┆ std       ┆ ---       ┆ on_densi │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ty       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 219146    ┆ 219146.0  ┆ 219146.0  ┆ … ┆ 126407.0  ┆ 126407.0  ┆ 126407.0  ┆ 126407.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 92739.0   ┆ 92739.0   ┆ 92739.0   ┆ 92739.0  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 37.204825 ┆ -95.77523 ┆ … ┆ 1.299688  ┆ 0.64185   ┆ 62.498928 ┆ 29.92241 │
│           ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆ 3        │
│ std       ┆ null      ┆ 6.615911  ┆ 15.309658 ┆ … ┆ 0.5662    ┆ 0.284931  ┆ 20.825274 ┆ 238.3609 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 18       │
│ min       ┆ 880e49010 ┆ 24.500153 ┆ -124.9997 ┆ … ┆ 0.237842  ┆ 0.127108  ┆ 11.0      ┆ 0.0      │
│           ┆ 7fffff    ┆           ┆ 19        ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 32.011747 ┆ -106.3379 ┆ … ┆ 0.887593  ┆ 0.403161  ┆ 43.0      ┆ 0.0      │
│           ┆           ┆           ┆ 13        ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 37.392851 ┆ -97.00099 ┆ … ┆ 1.180531  ┆ 0.592243  ┆ 71.0      ┆ 0.546882 │
│ 75%       ┆ null      ┆ 42.636219 ┆ -84.09314 ┆ … ┆ 1.559442  ┆ 0.826082  ┆ 82.0      ┆ 3.911056 │
│           ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆ 5        │
│ max       ┆ 88509edb6 ┆ 49.499987 ┆ -66.00020 ┆ … ┆ 5.942014  ┆ 1.893872  ┆ 95.0      ┆ 14806.08 │
│           ┆ 5fffff    ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
nc_row = df.null_count().row(0)
cols_with_nulls = [col for col, n in zip(df.columns, nc_row) if n > 0]
for col in cols_with_nulls:
    print(f"{col}: {df[col].null_count()}")

if cols_with_nulls:
    df = df.drop_nulls(subset=cols_with_nulls)

elevation: 92739
slope: 92739
aspect: 92739
roughness: 92739
wind_10m_avg: 92739
wind_10m_std: 92739
landcover: 92739
population_density: 92739
shape: (2, 2)
┌───────────┬────────┐
│ has_solar ┆ count  │
│ ---       ┆ ---    │
│ bool      ┆ u32    │
╞═══════════╪════════╡
│ true      ┆ 3926   │
│ false     ┆ 215220 │
└───────────┴────────┘
shape: (2, 2)
┌─────────────┬────────┐
│ has_turbine ┆ count  │
│ ---         ┆ ---    │
│ bool        ┆ u32    │
╞═════════════╪════════╡
│ true        ┆ 56131  │
│ false       ┆ 163015 │
└─────────────┴────────┘